<?php

namespace Database\Seeders;

use App\Models\Marketplace;
use App\Models\Trust;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Str;

class TrustSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $marketplace = Marketplace::first();
        // trust to seed 
        $healthcare_organizations = [
            "Airedale NHS Foundation Trust",
            "Alder Hey NHS FT Trust",
            "Allegra Care-Blossom Fields",
            "Aneurin Bevan University LHB",
            "Arden & GEM CSU",
            "Ashford and St Peter's Hospitals NHS Foundation Trust",
            "Avon and Wiltshire Mental Health Partnership NHS Trust",
            "Ayrshire and Arran",
            "Barking Havering and Redbridge University Hospitals NHS Trust",
            "Barnet, Enfield and Haringey Mental Health Trust",
            "Barnsley Hospital NHS Foundation Trust",
            "Barts Health NHS Trust",
            "Bath and North East Somerset, Swindon and Wiltshire Integrated Care Board (ICB)",
            "Bedfordshire Hospitals NHS Foundation Trust",
            "Belfast Health & Social Care Trust",
            "Berkshire Healthcare NHS Foundation Trust",
            "Betsi Cadwaladr University LHB",
            "Birmingham and Solihull Mental Health NHS Foundation Trust",
            "Birmingham Community Healthcare NHS Foundation Trust",
            "Birmingham Women's and Children's Hospital",
            "Black Country Healthcare NHS Foundation Trust",
            "Blackpool Victoria Hospital",
            "Blood and Transplant",
            "Bolton NHS Foundation Trust",
            "Borders",
            "Bradford District Care Trust",
            "Bradford District NHS Foundation Trust",
            "Bradford Teaching Hospitals NHS Foundation Trust",
            "Bridge street medical centre",
            "Bridgewater Community Healthcare NHS Foundation Trust",
            "Brighton and Sussex University Hospitals NHS Trust",
            "Bromley Health Care",
            "Buckinghamshire Healthcare NHS Trust",
            "Calderdale and Huddersfield NHS Foundation Trust",
            "Cambridge University Hospitals NHS Foundation Trust",
            "Cambridgeshire and Peterborough NHS Foundation Trust",
            "Cambridgeshire Community Services NHS Trust",
            "Camden & Islington NHS Foundation Trust",
            "Camden and Islington NHS Foundation Trust",
            "Cardiff and Vale University Local Health Board",
            "Central and North West London NHS Foundation Trust",
            "Central London Community Healthcare NHS Trust",
            "Chelsea and Westminster Hospital NHS Foundation Trust",
            "Cheshire and Wirral Partnership NHS Foundation Trust",
            "Chesterfield Royal Hospital NHS Foundation Trust",
            "City Health Care Partnership CIC",
            "Cornwall Foundation NHS Partnership Trust",
            "Cornwall Partnership NHS Foundation Trust",
            "Countess of Chester Hospital NHS Foundation Trust",
            "County Durham and Darlington NHS Foundation Trust",
            "Coventry and Warwickshire Partnership NHS Trust",
            "CRN Eastern",
            "CRN West Midlands",
            "Croydon Health Services NHS Trust",
            "Cumbria, Northumberland, Tyne and Wear NHS Foundation Trust",
            "Cwm Taf Morgannwg University LHB",
            "Dartford and Gravesham NHS Trust",
            "Derby and Burton",
            "Derby and Derbyshire CCG",
            "Derbyshire Community Health Services NHS Foundation Trust",
            "Derbyshire Healthcare NHS Foundation Trust",
            "Devon Partnership NHS Trust",
            "Doncaster and Bassetlaw Teaching Hospitals",
            "Doncaster and Bassetlaw Teaching Hospitals NHS Foundation Trust",
            "Dorset County Hospital NHS Foundation Trust",
            "Dorset Healthcare University NHS Foundation Trust",
            "Dudley Integrated Health and Care NHS Trust",
            "Dumfries and Galloway",
            "East and North Hertfordshire NHS Trust",
            "East Cheshire NHS Trust",
            "East Kent Hospitals University NHS Foundation Trust",
            "East Lancashire Hospitals NHS Trust",
            "East London NHS Foundation Trust",
            "East Midlands Ambulance Service NHS Trust",
            "East of England Ambulance Service",
            "East of England Ambulance Service (Norfolk & Waveney)",
            "East Suffolk and North Essex NHS Foundation Trust",
            "East Suffolk North Essex Foundation Trust",
            "East Sussex Healthcare NHS Trust",
            "Edinburgh Royal Infirmary",
            "England",
            "England / Improvement",
            "Epsom and St Helier University Hospitals NHS Trust",
            "Essex Partnership University NHS Foundation Trust",
            "Family Solutions - Dudley",
            "Fife",
            "Forth Valley",
            "Frimley Health NHS Foundation Trust",
            "Gateshead Health NHS Foundation Trust",
            "George Eliot Hospital NHS Trust",
            "Gloucestershire Health and Care NHS Foundation Trust",
            "Gloucestershire Hospitals NHS Foundation Trust",
            "GMCRN",
            "Grampian",
            "Great Ormond Street Hospital for Children NHS Foundation Trust",
            "Great Western Hospitals NHS Foundation Trust",
            "Greater Glasgow and Clyde",
            "Greater Manchester Mental Health NHS Foundation Trust",
            "Guy's and St Thomas' NHS Foundation Trust",
            "Hampshire Hospitals NHS Foundation Trust",
            "Harrogate and District NHS Foundation Trust",
            "Health Education and Improvement Wales",
            "Hertfordshire Community NHS Trust",
            "Hertfordshire Partnership University NHS Foundation Trust",
            "Highland",
            "Homerton University Hospital NHS Foundation Trust",
            "Hounslow and Richmond Community Healthcare NHS Trust",
            "Hull University Teaching Hospitals NHS Trust",
            "Humber Teaching NHS Foundation Trust",
            "Hywel Dda University Health Board",
            "Imperial College Healthcare NHS Trust",
            "Isle of Wight NHS Trust",
            "James Paget University Hospitals NHS Foundation Trust",
            "Kent and Medway",
            "Kent and Medway NHS and Social Care Partnership Trust",
            "Kent Community Health NHS Foundation Trust",
            "Kettering General Hospital NHS Foundation Trust",
            "King's College Hospital Foundation Trust",
            "Kingston Hospital NHS Foundation Trust",
            "Lanarkshire",
            "Lancashire & South Cumbria NHS Foundation Trust",
            "Lancashire Teaching Hospitals NHS Foundation Trust",
            "Leeds and York Partnership NHS Foundation Trust",
            "Leeds Community Healthcare NHS Trust",
            "Leeds Teaching Hospitals NHS Trust",
            "Leicestershire Partnership NHS Trust",
            "Lewisham and Greenwich NHS Trust",
            "Lincolnshire Community Health Services NHS Trust",
            "Lincolnshire Partnership Foundation Trust",
            "Lincolnshire Partnership NHS Foundation Trust",
            "Lister House Surgery",
            "Liverpool Heart and Chest Hospital NHS Foundation Trust",
            "Liverpool University Hospitals NHS Foundation Trust",
            "Liverpool Women's NHS Foundation Trust",
            "Locala Community Partnerships",
            "London Ambulance Service NHS Trust",
            "London North West NHS Trust",
            "London North West University Healthcare NHS Trust",
            "LOROS",
            "Lothian",
            "Maidstone and Tunbridge Wells NHS Trust",
            "Manchester University NHS Foundation Trust",
            "Marie Curie",
            "Medway NHS Foundation Trust",
            "Mersey Care NHS Foundation Trust",
            "Mid and South Essex NHS Foundation Trust",
            "Mid Cheshire Hospitals NHS Foundation Trust",
            "Mid Yorkshire Hospitals NHS Trust",
            "Midlands and Lancashire CSU",
            "Midlands Partnership Foundation Trust",
            "Midlands Partnership NHS Foundation Trust",
            "Milton Keynes University Hospital NHS Foundation Trust",
            "Monklands Hospital - ED",
            "Moorfields Eye Hospital NHS Foundation Trust",
            "National Services Scotland",
            "National Waiting Times Centre Board",
            "NEL Commissioning Alliance",
            "NELFT NHS Foundation Trust",
            "Norfolk and Norwich University Hospitals NHS Foundation Trust",
            "Norfolk and Suffolk NHS Foundation Trust",
            "Norfolk Community Health and Care NHS Trust",
            "North Bristol NHS Trust",
            "North Cumbria integrated care",
            "North Cumbria Integrated Care NHS Foundation Trust",
            "North East Ambulance Service NHS Foundation Trust",
            "North East London NHS Foundation Trust",
            "North Middlesex University Hospital NHS Trust",
            "North Staffordshire Combined Healthcare NHS Trust",
            "North Tees and Hartlepool NHS Foundation Trust",
            "North West Ambulance Service NHS Trust",
            "North West Anglia NHS Foundation Trust",
            "North West Boroughs Healthcare NHS Foundation Trust",
            "Northampton General Hospital NHS Trust",
            "Northamptonshire Healthcare NHS Foundation Trust",
            "Northern Care Alliance NHS Group",
            "Northern Devon Healthcare NHS Trust",
            "Northern Health Social Care Trust",
            "Northern Ireland Blood Transfusion Service",
            "Northern Island Blood Transfusion Service",
            "Northern Lincolnshire and Goole NHS Foundation Trust",
            "Northumbria Healthcare NHS Foundation Trust",
            "Nottingham CityCare Partnership",
            "Nottingham University Hospitals NHS Trust",
            "Nottinghamshire Healthcare NHS Foundation Trust",
            "Orkney",
            "Oxford University Hospitals NHS Foundation trust",
            "Oxleas NHS Foundation Trust",
            "Pennine Care NHS Foundation Trust",
            "Portsmouth Hospitals University National Health Service Trust",
            "Powys Teaching LHB",
            "Project Nightingale NHS Trust",
            "Public Health England",
            "Public Health Wales",
            "Public Health Wales NHS Trust",
            "Queen Elizabeth hospital Lewisham",
            "Queen Victoria Hospital NHS Foundation Trust",
            "Rotherham Clinical Commissioning Group",
            "Rotherham Doncaster and South Humber NHS Foundation Trust",
            "Royal Berkshire NHS Foundation Trust",
            "Royal Brompton & Harefield NHS Foundation Trust",
            "Royal Cornwall Hospitals NHS Trust",
            "Royal Devon and Exeter NHS Foundation Trust",
            "Royal Free London NHS Foundation Trust",
            "Royal Infirmary of Edinburgh",
            "Royal National Orthopaedic Hospital NHS Trust",
            "Royal Papworth Hospital NHS Foundation Trust",
            "Royal Surrey County Hospital NHS Foundation Trust",
            "Royal United Hospital Bath",
            "Royal United Hospitals Bath NHS Foundation Trust",
            "Royal Wolverhampton NHS Trust",
            "Salford Royal NHS Foundation Trust",
            "Salisbury NHS Foundation Trust",
            "Sandwell and West Birmingham Hospitals NHS Trust",
            "Scottish Ambulance Service",
            "Services Hub for East Sussex Healthcare NHS Trust",
            "Sheffield Children's NHS Foundation Trust",
            "Sheffield Health & Social Care NHS Foundation Trust",
            "Sheffield Teaching Hospitals NHS Foundation Trust",
            "Sherwood Forest Hospitals NHS Foundation Trust",
            "Shetland",
            "Shrewsbury and Telford Hospital NHS Trust",
            "Shropshire Community Health NHS Trust",
            "Solent NHS Trust",
            "Somerset Partnership NHS Foundation Trust",
            "South Central Ambulance Service NHS Foundation Trust",
            "South East Coast Ambulance Service NHS Foundation Trust",
            "South Eastern Health & Social Care",
            "South London and Maudsley NHS Foundation Trust",
            "South Tees Hospitals NHS Foundation Trust",
            "South Tyneside and Sunderland NHS Foundation Trust",
            "South Warwickshire NHS Foundation Trust",
            "South West London and St Georges Mental Health Trust",
            "South West Yorkshire Partnership NHS Foundation Trust",
            "South Western Ambulance Service NHS Foundation Trust",
            "South Yorkshire ICB",
            "Southern Health & Social Care Trust",
            "Southern Health NHS Foundation Trust",
            "Southport & Ormskirk Hospital NHS Trust",
            "St George's University Hospitals NHS Foundation Trust",
            "St Helens and Knowsley Teaching Hospitals NHS Trust",
            "Staffordshire and Stoke-on-Trent CCGs",
            "Stockport NHS Foundation Trust",
            "Stratford Central PCN",
            "Surrey and Borders Partnership NHS Foundation Trust",
            "Surrey and Sussex Healthcare NHS Trust",
            "Sussex Community NHS Foundation Trust",
            "Sussex Partnership NHS Foundation Trust",
            "Swansea Bay University Health Board",
            "Swansea Bay University Local Health Board",
            "Tameside & Glossop ICFT",
            "Tameside and Glossop Integrated Care NHS Foundation Trust",
            "Tavistock and Portman NHS Foundation Trust",
            "Tees, Esk and Wear Valleys NHS Foundation Trust",
            "The Christie NHS Foundation Trust",
            "The Clatterbridge Cancer Centre NHS Foundation Trust",
            "The Dudley Group NHS Foundation Trust",
            "The Hillingdon Hospitals NHS Foundation Trust",
            "The Newcastle Upon Tyne Hospitals NHS Foundation Trust",
            "The Princess Alexandra Hospital NHS Trust",
            "The Queen Elizabeth Hospital King's Lynn NHS Foundation Trust",
            "The Robert Jones and Agnes Hunt Orthopaedic Hospital NHS Foundation Trust",
            "The Rotherham NHS Foundation Trust",
            "The Royal Marsden NHS Foundation Trust",
            "The Royal Orthopaedic Hospital NHS Foundation Trust",
            "The Royal Wolverhampton NHS Trust",
            "The Shrewsbury and Telford Hospital NHS Trust",
            "The Walton Centre NHS Foundation Trust",
            "Torbay and South Devon NHS Foundation Trust",
            "United Lincolnshire Hospitals NHS Trust",
            "University College London Hospitals NHS Foundation Trust (UCLH)",
            "University Hospital Southampton NHS Foundation Trust",
            "University Hospitals Birmingham NHS Foundation Trust",
            "University Hospitals Bristol And Weston NHS Foundation Trust",
            "University Hospitals Coventry and Warwickshire NHS Trust",
            "University Hospitals Dorset NHS Foundation Trust",
            "University Hospitals of Derby and Burton NHS Foundation Trust",
            "University Hospitals of Leicester NHS Trust",
            "University Hospitals of Morecambe Bay NHS Foundation Trust",
            "University Hospitals of North Midlands NHS Trust",
            "University Hospitals Plymouth NHS Trust",
            "Velindre NHS Trust",
            "Wales Shared Services Partnership",
            "Walsall Healthcare NHS Trust",
            "Warrington and Halton Teaching Hospitals NHS Foundation Trust",
            "Welsh Ambulance Services NHS Trust",
            "West Hertfordshire Hospitals NHS Trust",
            "West London NHS Trust",
            "West Midlands Ambulance Service University NHS Foundation Trust",
            "West Suffolk NHS Foundation Trust",
            "Western Health & Social Care Trust",
            "Western Isles",
            "Western Sussex Hospitals NHS Foundation Trust",
            "Whittington Health NHS Trust",
            "Wirral Community Health and Care NHS Foundation Trust",
            "Wirral University Teaching Hospital NHS Foundation Trust",
            "Worcestershire Acute Hospitals NHS Trust",
            "Worcestershire Health and Care NHS Trust",
            "Wrightington, Wigan and Leigh NHS Foundation Trust",
            "Wychavon District Council",
            "Wye Valley NHS Trust",
            "Yeovil District Hospital NHS Foundation Trust",
            "Yeovil Hospital",
            "York Teaching Hospital NHS Foundation Trust",
            "Yorkshire Ambulance Service NHS Trust",
            "Yorkshire and Humber CRN",
            "Bedfordshire, Luton and Milton Keynes (ICB)",
            "Birmingham and Solihull (ICB)",
            "Black Country (ICB)",
            "Bristol, North Somerset and South Gloucestershire (ICB)",
            "Buckinghamshire, Oxfordshire and Berkshire West (ICB)",
            "Cambridgeshire and Peterborough (ICB)",
            "Cheshire and Merseyside (ICB)",
            "Cornwall and The Isles Of Scilly (ICB)",
            "Coventry and Warwickshire (ICB)",
            "Derby and Derbyshire (ICB)",
            "Devon (ICB)",
            "Dorset (ICB)",
            "Frimley (ICB)",
            "Gloucestershire (ICB)",
            "Greater Manchester (ICB)",
            "Hampshire and Isle of Wight (ICB)",
            "Herefordshire and Worcestershire (ICB)",
            "Hertfordshire and West Essex (ICB)",
            "Humber and North Yorkshire (ICB)",
            "Kent and Medway (ICB)",
            "Lancashire and South Cumbria (ICB)",
            "Leicester, Leicestershire and Rutland (ICB)",
            "Lincolnshire (ICB)",
            "Mid and South Essex (ICB)",
            "Norfolk and Waveney (ICB)",
            "North Central London (ICB)",
            "North East and North Cumbria (ICB)",
            "North East London (ICB)",
            "North West London (ICB)",
            "Northamptonshire (ICB)",
            "Nottingham and Nottinghamshire (ICB)",
            "Shropshire, Telford and Wrekin (ICB)",
            "Somerset (ICB)",
            "South East London (ICB)",
            "South West London (ICB)",
            "South Yorkshire (ICB)",
            "Staffordshire and Stoke-on-Trent (ICB)",
            "Suffolk and North East Essex (ICB)",
            "Surrey Heartlands (ICB)",
            "Sussex (ICB)",
            "West Yorkshire (ICB)"
        ];

        foreach ($healthcare_organizations as $organization) {
            $trust = Trust::factory()->create([
                'title' => $organization,
                'status' => 1,
            ]);

            $trust->marketplaces()->attach(
                $marketplace->id,
                ['id' => Str::ulid()]
            );
        }

        // Get 1–10 random client users
        // Prepare subscriber records with ULID
        // $subscribers = User::role('client')
        //     ->get()
        //     ->random(rand(1, 10))
        //     ->map(function ($user) use ($marketplace, $trust) {
        //         return [
        //             'id' => Str::ulid(),
        //             'user_id' => $user->id,
        //             'marketplace_id' => $marketplace->id,
        //             'trust_id' => $trust->id,
        //             'status' => 1,
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ];
        //     });

        // // Insert all subscribers
        // \DB::table('marketplace_subscribers')->insert($subscribers->toArray());
    }
}
